# Generated by Django 3.0.6 on 2020-06-11 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_post_liked_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='post.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked_posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='Liked posts'),
        ),
    ]
