# Generated by Django 3.0.6 on 2020-06-11 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_auto_20200611_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='post.Category'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='liked_posts',
        ),
        migrations.AddField(
            model_name='post',
            name='liked_posts',
            field=models.ManyToManyField(null=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='Liked posts'),
        ),
    ]
