# Generated by Django 3.0.6 on 2020-06-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_post_liked_posts'),
        ('accounts', '0004_auto_20200525_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_posts',
            field=models.ManyToManyField(related_name='liked_posts', to='post.Post', verbose_name='Liked Post'),
        ),
    ]
